name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Copy frontend files to docs directory
      run: |
        rm -rf docs
        mkdir docs
        npx cpy "**/*.{html,css,js,jpg,jpeg,png,gif,svg}" css js public docs --parents
        # Remove backend and other non-frontend files if any
        # Adjust this command if needed to include all frontend assets

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
